services:
    login_listener:
        class: 'Mant\AlmacenBundle\Listener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    app.fpdf:
        class: Mant\AlmacenBundle\Services\fpdf\FPDF
        arguments: ["null"]
