<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaVentaRepository extends EntityRepository
{
}
