<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\EntityRepository;
use Mant\AlmacenBundle\Entity\movimientos\TransferenciaStock;
use Mant\AlmacenBundle\Entity\movimientos\OrdenCompra;

/**
 * MovimientoStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaPedidoRepository extends EntityRepository
{

}
