<?php

namespace Mant\AlmacenBundle\Entity\finanzas;

use Doctrine\ORM\EntityRepository;

/**
 * CuentaCorrienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaCorrienteRepository extends EntityRepository
{

    public function ctaCteEnteComercial($ente)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT cc FROM MantAlmacenBundle:finanzas\CuentaCorriente cc WHERE cc.ente = :ente'
            )
            ->setParameter('ente', $ente)
            ->getOneOrNullResult();
    }    	
}
