<?php

namespace Mant\AlmacenBundle\Entity\finanzas;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoCuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoCuentaRepository extends EntityRepository
{
}
